apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: snappcloud
  namespace: olm
spec:
  displayName: SnappCloud
  image: ghcr.io/snapp-incubator/snappcloud-hub:latest
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll: 
      interval: 5m