apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: snappcloud-hub-catalog
  namespace: openshift-marketplace
spec:
  displayName: SnappCloud-Hub
  image: ghcr.io/snapp-incubator/snappcloud-hub:v0.1.0
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
