name: Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: opm validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install opm
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-4.13/opm-linux.tar.gz | tar -xvz
          chmod +x ./opm
          mv opm /usr/local/bin/opm
      - name: Catalog Validation
        run: opm validate catalog